### ISSUE TITLE
Running example error - "struct `Decoder` is private"

### ISSUE THREAD

**Issue by droneboost** [sidit77/bluefang#1]
Hi @sidit77 

When running "cargo run --example audio_sink --release" on my window PC, I got following build error.
Could you please double check this issue?

warning: `bluefang` (lib) generated 7 warnings
   Compiling bluefang v0.1.0 (C:\Users\Demo\Downloads\bluefang-main)
error[E0603]: struct `Decoder` is private
  --> examples\audio_sink.rs:36:13
   |
**36 | use sbc_rs::Decoder;
   |             ^^^^^^^ private struct**
   |
note: the struct `Decoder` is defined here
  **--> C:\Users\Demo\.cargo\git\checkouts\sbc-rs-20ef8ed4e76911e8\140d3bb\src\lib.rs:1:22**
   |
1  | use crate::decoder::{Decoder, Error, OutputFormat};
   |                      ^^^^^^^
help: import `Decoder` directly
   |
36 | use sbc_rs::decoder::Decoder;
   |     ~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0603`.
error: could not compile `bluefang` (example "audio_sink") due to 1 previous error

**Comment by sidit77** [comment]
Oops, I forgot to update the example after I slightly adjusted the API of sbc-rs. Should be fixed now.

**Comment by droneboost** [comment]
@sidit77 ,  Thanks for your quick bugfixing.  The build on my window PC seems OK now.

BTW, Which driver should  I choose to replace the window standard driver?  libusb-win32 or WinUSB ?

![image](https://github.com/user-attachments/assets/bc0d986c-69f5-48f7-841b-cb0edaa31442)

**Comment by sidit77** [comment]
I use WinUSB.

**Comment by droneboost** [comment]
@sidit77 ,  Thanks for reply.

I'm working on a Dell laptop, there is an internal Bluetooth chip(Intel BT radio) inside the laptop, should I disable the intel BT chip while using the UGREEN bluetooth adapter 5.0?

**Comment by sidit77** [comment]
I don't think that's necessary. If you look at [this line](https://github.com/sidit77/bluefang/blob/c5fdc16cc1fc2562b8b39ddd3034567b8973f67c/examples/audio_sink.rs#L67) you'll see that the adapters are filtered by their vendor id (using the vendors of the two usb dongles I own). So as long as Intel's id is not in this list the code should skip right over it.

**Comment by droneboost** [comment]
@sidit77 ， I add my BT dongle VID in that line, and the the example seems work well now, but I saw two ERROR prompt message in the console log, Do I need to update the firmware for my BT dongle?

warning: `bluefang` (lib) generated 7 warnings
   Compiling bluefang v0.1.0 (C:\Users\Demo\Downloads\bluefang-main)
    Finished `release` profile [optimized] target(s) in 44.23s
     Running `C:\Users\Demo\Downloads\bluefang-main\target\release\examples\audio_sink.exe`
**ERROR bluefang::firmware: Failed to read file rtl8761bu_fw.bin: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
ERROR bluefang::hci: Failed to load firmware: Generic("Failed to find load firmware")**
Waiting for connections...
Press Ctrl-C to exit

**Comment by sidit77** [comment]
You can download the realtek firmware files from [here](https://kernel.googlesource.com/pub/scm/linux/kernel/git/firmware/linux-firmware/+archive/refs/heads/main/rtl_bt.tar.gz). Simply extract them into a `firmware` folder next to `src` or `examples`.

**Comment by droneboost** [comment]
@sidit77 ,  Thanks so much! I'm able to send the audio streaming from my cellphone to my window laptop through you example now!

Next step, I'd like to get the audio PCM streaming from the BT stack, Could you please advice me how to do that?

**Comment by droneboost** [comment]
@sidit77 , I saw there is a callback function in the example, I can get the PCM data from this callback, is it right?

    fn on_data(&mut self, data: Bytes) {
        //TODO actually parse the header to make sure the packets are not fragmented
        self.process_frames(&data.as_ref()[1..]);
    }

**Comment by sidit77** [comment]
In A2DP (Bluetooth Classic Audio) you expose possible codecs and the connected device then picks one of them and starts a audio session. This example only exposes the SBC codec. This callback then recieves the SBC packets. Each SBC packet contains multiple SBC frames which you have to decode to get to the raw samples. This happens [here](https://github.com/sidit77/bluefang/blob/c5fdc16cc1fc2562b8b39ddd3034567b8973f67c/examples/audio_sink.rs#L263).

For audio playback specifically you'll have to resample the audio data to match the sample rate of you playback device, but if you want to write them to a file it shouldn't be required as long as you set the file header correctly.

**Comment by droneboost** [comment]
@sidit77 ,  Understood. Thank you so much for your advice, I shall study your example code carefully.

**Comment by droneboost** [comment]
Since the initial reported issue was fixed by sidit77, Let me close this issue as fixed.
