### ISSUE TITLE
iPhone can't connect to bluefang on PC

### ISSUE THREAD

**Issue by droneboost** [sidit77/bluefang#2]
iOS can't connect to bluefang on PC,  show "Pairing took too long..." error message immediately.

**Comment by droneboost** [comment]
@sidit77 ,  I submit a new issue.

**Comment by sidit77** [comment]
I don't have any iOS devices, so I can't test this myself.

If you send me your package log (enabled using the `BTSNOOP_LOG` environment variable) I can take a look at it once I'm home again.

**Comment by droneboost** [comment]
@sidit77 ,  I'm not quite familar with RUST.  Do you mean set BTSNOOP_LOG=TRUE, before run audio_sink.ext in the command line?

**Comment by sidit77** [comment]
More like `BTSNOOP=audiosink.pkglg` or  something similar, but yes. This should create a new file called `audiosink.pkglg` in your current working directory that contains all the packets that are sent or received by the Bluetooth stack. If you have wireshark installed, it should be able to open that file.

**Comment by droneboost** [comment]
[audiosink.zip](https://github.com/user-attachments/files/18120058/audiosink.zip)
@sidit77 ,  Let me attach the packet log, could you please take a look?

**Comment by sidit77** [comment]
![image](https://github.com/user-attachments/assets/ca34ab0a-f6e7-464b-9313-acbc197fe9f9)

It seems like one of the packages sent by my bluetooth stack is malformed. I suspect that this is what's causing the issue.

I'll try to figure out why that happens, but I'm currently a bit busy, so I'm not sure how long it's going to take.

**Comment by sidit77** [comment]
It seems like Apple is using a "Service Search Request" for querying the capabilities of the connected device. I just looked at all the logs from all devices that I tested and all of them use a "Service Search Attribute Request" instead, so the "Service Search Request" path in more or less completetly untested from my side.  It is likely that that I missinterpreted the specification on how a valid "Service Search Response" should look like, as I had no real-world data to check against.

**Comment by droneboost** [comment]
@sidit77 ,  Thanks for analyzing the bt hci log, so we need to modify bluefang-main\src\hci\connection.rs to fix the iOS pairing issue, is my understanding correct?

**Comment by sidit77** [comment]
The bad section should be [here](https://github.com/sidit77/bluefang/blob/main/src%2Fsdp%2Fmod.rs#L95) and [this](https://www.bluetooth.com/wp-content/uploads/Files/Specification/HTML/Core-54/out/en/host/service-discovery-protocol--sdp--specification.html#UUID-e354ab30-bd00-e452-20b7-5a8af1d87768) is the relevant specification.

I suspect the issue is that I set `current_service_record_count` to `maximum_service_record_count` instead of `attribute_list.len()`.

**Comment by droneboost** [comment]
@sidit77 ,  Thanks!  I test the method in your comment above, it works well with iOS device.
I created a PR for this bugfix.
